name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Test
      shell: pwsh
      run: ./build.ps1 -Task TestModule -Bootstrap -SkipIsolation -ErrorAction Stop

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Publish module
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Publish
        id: publish
        env:
            PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
        shell: pwsh
        run: |
          ./build.ps1 -Task Default, Publish -Bootstrap -SkipIsolation -ErrorAction Stop
          # Zip published module for upload as release draft on GH
          Get-ChildItem $env:BHBuildOutput | Compress-Archive -DestinationPath "$env:BHProjectName.zip"
          "ModuleZip=$env:BHProjectName.zip" >> $env:GITHUB_OUTPUT

      - name: Create release
        run: gh release create ${{ github.ref_name }} --generate-notes --draft ./${{ steps.publish.outputs.ModuleZip }}
        env:
          GH_TOKEN: ${{ github.token }}

